"""init load organiser

Revision ID: c6459ca8ce2a
Revises: 1a31ce608336
Create Date: 2025-06-01 16:44:50.793109

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c6459ca8ce2a'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft',
    sa.Column('registration', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aircraft_registration'), 'aircraft', ['registration'], unique=True)
    op.create_table('instructor',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('tandem_certified', sa.Boolean(), nullable=False),
    sa.Column('aff_certified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weatherreport',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('wind_speed', sa.Integer(), nullable=False),
    sa.Column('wind_direction', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.Float(), nullable=False),
    sa.Column('cloud_ceiling', sa.Integer(), nullable=True),
    sa.Column('condition', sa.Enum('GOOD', 'MARGINAL', 'POOR', name='weathercondition'), nullable=False),
    sa.Column('suitable_for_tandems', sa.Boolean(), nullable=False),
    sa.Column('suitable_for_students', sa.Boolean(), nullable=False),
    sa.Column('suitable_for_fun_jumpers', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('load',
    sa.Column('aircraft_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('altitude', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PLANNING', 'CONFIRMED', 'BOARDED', 'DEPARTED', 'COMPLETED', 'CANCELLED', name='loadstatus'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jump',
    sa.Column('load_id', sa.Uuid(), nullable=False),
    sa.Column('jumper_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('jump_type', sa.Enum('TANDEM', 'AFF', 'FUN_JUMPER', name='jumptype'), nullable=False),
    sa.Column('exit_order', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Uuid(), nullable=True),
    sa.Column('aff_level', sa.Enum('LEVEL_1', 'LEVEL_2', 'LEVEL_3', 'LEVEL_4', 'LEVEL_5', 'LEVEL_6', 'LEVEL_7', 'GRADUATE', name='afflevel'), nullable=True),
    sa.Column('customer_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructor.id'], ),
    sa.ForeignKeyConstraint(['load_id'], ['load.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jump')
    op.drop_table('load')
    op.drop_table('weatherreport')
    op.drop_table('instructor')
    op.drop_index(op.f('ix_aircraft_registration'), table_name='aircraft')
    op.drop_table('aircraft')
    # ### end Alembic commands ###
